---
- name: "restart ufw"
  service:
    name: "ufw"
    state: "restarted"

- name: "stop ufw"
  service:
    name: "ufw"
    state: "stopped"

- name: "reload ufw rules"
  shell: "ufw reload"

- name: "reload ufw"
  shell: "ufw reload"

- name: "disable ufw rules"
  shell: "ufw disable"

- name: "sysctl flush ipv4 route table"
  become: true
  sysctl:
      name: "net.ipv4.route.flush"
      value: "1"
      sysctl_set: true
  when:
    - ansible_virtualization_type != "docker"

- name: "sysctl flush ipv6 route table"
  become: true
  sysctl:
      name: "net.ipv6.route.flush"
      value: "1"
      sysctl_set: true
  when:
    - ansible_virtualization_type != "docker"

- name: "systemd restart tmp.mount"
  become: true
  systemd:
      name: "tmp.mount"
      daemon_reload: true
      enabled: true
      masked: false
      state: "reloaded"
  when:
    - ansible_virtualization_type != "docker"

- name: "systemd restart var-tmp.mount"
  become: true
  systemd:
      name: "var-tmp.mount"
      daemon_reload: true
      enabled: true
      masked: false
      state: "reloaded"

- name: "generate new grub config"
  become: true
  command: grub-mkconfig -o "{{ grub_cfg.stat.path }}"

- name: "restart sshd"
  become: true
  service:
      name: "sshd"
      state: restarted

- name: "restart auditd"
  become: true
  service:
      name: "auditd"
      state: "restarted"
  tags:
      - skip_ansible_lint

- name: "load audit rules"
  become: true
  command: "/sbin/augenrules --load"
  tags:
      - skip_ansible_lint
