#!/bin/bash
DEBIAN_FRONTEND=noninteractive apt --assume-yes update
#DEBIAN_FRONTEND=noninteractive apt --assume-yes full-upgrade
DEBIAN_FRONTEND=noninteractive apt --assume-yes install git ansible vim
git clone https://github.com/copykatze/nerdadventure.git /opt/nerdadventure
